name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: Upgrade pip and install latest dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt
          pip install --upgrade -r requirements-dev.txt || true
          pip check || true
      - name: Lint and type-check
        run: |
          flake8 || true
          black --check . || true
          isort --check-only . || true
          mypy || true
      - name: Run tests
        run: |
          pytest --cov=src --cov=agents --cov=utils --cov-report=xml
